name: nostr_mail
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  ndk: ^0.6.1-dev.4
  enough_mail: ^2.1.7
  sembast: ^3.8.6
  http: ^1.6.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
