name: nostr_mail
description: A Dart SDK for sending and receiving emails over the Nostr protocol using NIP-59 gift-wrapped messages.
version: 1.4.3
repository: https://github.com/nogringo/nostr-mail-dart
homepage: https://github.com/nogringo/nostr-mail-dart
issue_tracker: https://github.com/nogringo/nostr-mail-dart/issues

topics:
  - nostr
  - email
  - encryption
  - messaging
  - decentralized

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.10.8

dependencies:
  ndk: ^0.7.1-dev.14
  enough_mail: ^2.1.7
  sembast: ^3.8.6
  http: ^1.6.0
  html: ^0.15.6

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
